# Generated by Django 4.2.23 on 2025-10-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "tblClaimAdmin" (
                "ClaimAdminId" SERIAL PRIMARY KEY,
                "ClaimAdminUUID" VARCHAR(36) UNIQUE NOT NULL,
                "ClaimAdminCode" VARCHAR(50),
                "LastName" VARCHAR(100),
                "OtherNames" VARCHAR(100),
                "DOB" DATE,
                "EmailId" VARCHAR(200),
                "Phone" VARCHAR(50),
                "HFId" INTEGER,
                "HasLogin" BOOLEAN,
                "ValidityFrom" TIMESTAMP NOT NULL DEFAULT NOW(),
                "ValidityTo" TIMESTAMP,
                "AuditUserId" INTEGER,
                CONSTRAINT "fk_tblClaimAdmin_HF" FOREIGN KEY ("HFId") REFERENCES "tblHF"("HfID")
            );
            CREATE INDEX IF NOT EXISTS "idx_tblClaimAdmin_HFId" ON "tblClaimAdmin"("HFId");
            CREATE INDEX IF NOT EXISTS "idx_tblClaimAdmin_UUID" ON "tblClaimAdmin"("ClaimAdminUUID");
            """,
            reverse_sql='DROP TABLE IF EXISTS "tblClaimAdmin" CASCADE;'
        ),
    ]
